version: '3.8'

services:
  node-app:
    build: .
    image: node-app
    env_file: 
      - ../env/.env
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/amberwave-node-app
    ports:
      - '${LOCALHOST_APP_PORT}:8080'
    depends_on:
      - mongodb
    volumes:
      - .:/usr/src/node-app
    networks:
      - node-network

  mongodb:
    image: mongo:4.2-bionic
    ports:
      - '${LOCALHOST_DB_PORT}:27017'
    volumes:
      - dbdata:/data/db
    networks:
      - node-network

volumes:
  dbdata:

networks:
  node-network:
    driver: bridge
