export const GET_ERRORS = 'GET_ERRORS';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_NETWORK = 'GET_NETWORK';
export const NETWORK_LOADING = 'NETWORK_LOADING';
export const NETWORK_NOT_FOUND = 'NETWORK_NOT_FOUND';
export const CLEAR_CURRENT_NETWORK = 'CLEAR_CURRENT_NETWORK';
export const GET_NETWORKS = 'GET_NETWORKS';
